### ISSUE TITLE
Feature Request: About dialog.

### ISSUE THREAD

**Issue by ravensorrow** [warg0x4e/HotBin#14]
An about dialog w/ version number, the dialog could also contain a link to the HotBin repo and maybe an option to check for updates.

**Comment by warg0x4e** [comment]
HotBin depends on Native Language Support in Windows, using pre-existing
strings for the user's language. An about section would have to be
English-only as I haven't time to translate it to other languages myself.

I haven't implemented an about section because I've licensed HotBin code
with The Unlicense license. This effectively puts the HotBin source code in
the public domain, and I have no desire to brand it as my own. It is a
simple tool that is useful to me that I thought might be useful to others.

Update checking is planned for the future. Either my own design, or WinGup.
