### ISSUE TITLE
modifications for personal use

### ISSUE THREAD

**Issue by jodathewise1969** [warg0x4e/HotBin#3]
mi sono permesso di modificare il sorgente facendo in modo che il cestino sia svuotato con un solo click sull'icona.
ho poi aggiunto l'esecuzione di un file esterno quando lo svuotamento è completato.
il file esterno è un compilato di powershell che memorizza il volume corrente, alza il volume a 100%, riproduce un suono e poi riporta il volume a quello precedente.

I took the liberty of modifying the source so that the trash is emptied with a single click on the icon.
I then added the execution of an external file when the emptying is completed.
the external file is a powershell compiled script that stores the current volume, raises the volume to 100%, plays a sound and then returns the volume to the previous one.
I'm a beginner in autohotkey programming

[HotBin.zip](https://github.com/warg0x4e/HotBin/files/15485759/HotBin.zip)
[trashsound.zip](https://github.com/warg0x4e/HotBin/files/15485745/trashsound.zip)

**Comment by warg0x4e** [comment]
Buongiorno

I wish you success in learning AutoHotkey. 

Ti auguro il successo.

The following links lead to AutoHotkey documentation regarding sound and volume.

https://www.autohotkey.com/docs/v2/lib/SoundGetVolume.htm

https://www.autohotkey.com/docs/v2/lib/SoundSetVolume.htm

https://www.autohotkey.com/docs/v2/lib/SoundPlay.htm

The Recycle Bin sound effect is enabled in HotBin, but it has to be enabled in Windows. The Recycle Bin sound effect is disabled by default since Windows 8.

![screenshot_Empty_Recycle_Bin_Sound](https://github.com/warg0x4e/HotBin/assets/2155010/0491b576-eb4b-4711-b962-a184a953161e)

**Comment by warg0x4e** [comment]
Sound is already enabled in HotBin, but you need to enable it in Windows.

![screenshot_Empty_Recycle_Bin_Sound](https://github.com/warg0x4e/HotBin/assets/2155010/6855bd25-7a12-431b-a61b-baccf60c5880)
