### ISSUE TITLE
Enhancement - Custom Icons

### ISSUE THREAD

**Issue by ghost** [warg0x4e/HotBin#4]
Enhancement: For a future release is it possible to add support for custom icons? Would also be nice to include percentage states of the recycle bin like empty, 25%, 50%, 75% and full. This would be similar to TrayBin 1.0.0.0 or MiniBin

**Comment by warg0x4e** [comment]
Hello, dburow03

I will consider adding the ability to drop in replacement icons and adding a line to the Tooltip and Tray Menu for percentage.

**Comment by warg0x4e** [comment]
A future release might include percentage on the menu, but not the Tooltip.

A future release might include support for drop-in replacement icons.

Determining the percentage requires parsing the registry for each volume and calculating the percentage, and determining how the user's locale displays percentages – #%, %#, # %, or % #.

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\BitBucket

LOCALE_IPOSITIVEPERCENT
https://learn.microsoft.com/en-us/windows/win32/intl/locale-ipositivepercent

LOCALE_SPERCENT
https://learn.microsoft.com/en-us/windows/win32/intl/locale-spercent

Because the recycle bin size can be changed by the user, the registry has to be parsed and the percentage calculated every time before displaying.

I won't add this feature to the Tooltip because the information on the Tooltip currently depends on a 500 millisecond timer.

If I can find a way to override and manage the Tooltip independently, I'll consider adding it to the Tooltip too.

Thanks again for your contribution.

**Comment by warg0x4e** [comment]
https://github.com/warg0x4e/HotBin/releases/tag/2.9.0.0
