### ISSUE TITLE
[Feature Request] option to swap single and double click function

### ISSUE THREAD

**Issue by jodathewise1969** [warg0x4e/HotBin#7]
is it possible to insert an option to swap effects of single click and double click?
Choose to do single click to empty bin instead of double (for example) and double click to open Recycled Bin
thanks in advance

PS
as suggested i'd added the code in static On_AHK_NOTIFYICON(wParam, lParam, *) function:
                {
					master_volume := SoundGetVolume()			
					SoundSetVolume "100"					
                        RecycleBin.Empty
					SoundPlay "emptybin.wav"
					Sleep 1000
					SoundSetVolume master_volume
				}	
to hold the actual volume, maximize volume, play a specific sound and restore the old volume after played	.
I usually have master volume to 0 but i like the sound after empty recycled bin

**Comment by warg0x4e** [comment]
Buongiorno

HotBin uses multilingual strings provided by Windows. There's no multilingual strings relevant to your request that could be used on the Tray Menu as a toggle, like "Show recycle confirmation" or "Run at user logon."

If you want it to work that way in your customized HotBin, you just need to swap or modify the code in the attached screenshot.

It's important bDoubleClicked remains. bDoubleClicked prevents the single-click action from processing after a double-click.

Be advised a new version is coming soon, and the code might change.

![Screenshot_20240618_122310_GitHub.jpg](https://github.com/warg0x4e/HotBin/assets/2155010/549691a1-28c8-41b9-a885-4be65e2c067d)

**Comment by jodathewise1969** [comment]
thank tou

**Comment by warg0x4e** [comment]
You're welcome

**Comment by warg0x4e** [comment]
> Be advised a new version is coming soon, and the code might change.
> 
> 

The code has changed in 2.10.0.0.

I've tried to make it simpler for you to modify. The click actions are now defined in the following methods:

- TrayMenu.WM_LBUTTONUP (left-click)
- TrayMenu.WM_MBUTTONUP (middle-click)
- TrayMenu.WM_RBUTTONUP (right-click).

Instead of using a variable to prevent single-click action occuring after and in addition to double-click, it will now wait indefinitely for double-click to complete with KeyWait("LButton").

https://github.com/warg0x4e/HotBin/releases/tag/2.10.0.0

https://github.com/warg0x4e/HotBin/tree/main
